<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-CLOFSUPE" ignored="0" name="RetryMulitpleFailedTestCases" tests="6" failures="1" timestamp="2021-05-08T16:15:19 IST" time="0.06" errors="0">
  <testcase name="Test1" time="0.008" classname="mytests.MyTests"/>
  <testcase name="Test2" time="0.002" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="mytests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="mytests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test2(MyTests.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="mytests.MyTests"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
